// Shared types for sentence-level annotations

/**
 * Represents a bounding box in unscaled PDF coordinates
 */
export interface BoundingRect {
  x: number;
  y: number;
  width: number;
  height: number;
}

/**
 * Section information for a sentence
 */
export interface SectionInfo {
  /** Section number (e.g., "1", "2.1", "A.1") - empty for unnumbered sections */
  number: string;
  /** Section title (e.g., "Introduction", "Related Work") */
  title: string;
  /** Full section text (number + title) */
  fullTitle: string;
}

/**
 * A sentence that may span multiple lines in the PDF.
 * Each sentence has one or more bounding rectangles (one per line it spans).
 */
export interface Sentence {
  /** Unique identifier (e.g., "page-1-sentence-5") */
  id: string;
  /** Full sentence text */
  text: string;
  /** Page number this sentence appears on */
  pageNumber: number;
  /** Index of first TextItem in this sentence */
  startTokenIndex: number;
  /** Index after last TextItem in this sentence (exclusive) */
  endTokenIndex: number;
  /** Bounding rectangles - one per line the sentence spans */
  boundingRects: BoundingRect[];
  /** Computed overall bounds encompassing all rects */
  bounds: {
    minX: number;
    minY: number;
    maxX: number;
    maxY: number;
  };
  /** Section this sentence belongs to (if detected) */
  section?: SectionInfo;
  /** AI-assigned label for this sentence */
  aiLabel?: SentenceLabel;
}

/**
 * Labels for classifying sentences in academic papers
 */
export type SentenceLabel =
  | 'background'      // Prior work, context, motivation
  | 'objective'       // Research goals, hypotheses
  | 'method'          // Methodology, approach, algorithm
  | 'result'          // Experimental results, findings
  | 'conclusion'      // Summary, takeaways
  | 'claim'           // Novel claims, contributions
  | 'limitation'      // Limitations, future work
  | 'definition'      // Definitions, terminology
  | 'example'         // Examples, illustrations
  | 'comparison';     // Comparisons with other work

/**
 * Labels for figures and tables
 */
export type FigureTableLabel =
  | 'architecture'    // System/model architecture diagram
  | 'results'         // Experimental results visualization
  | 'comparison'      // Comparison with baselines
  | 'ablation'        // Ablation study results
  | 'example'         // Example inputs/outputs
  | 'methodology'     // Method illustration
  | 'data';           // Dataset statistics

/**
 * AI review flags for identifying potential issues
 */
export interface AIReviewFlags {
  /** Potential correctness issue */
  correctnessIssue?: boolean;
  /** Notable novelty claim */
  novelty?: boolean;
  /** Consistency concern with other parts */
  consistencyIssue?: boolean;
}

/**
 * A reply to a sentence annotation
 */
export interface SentenceAnnotationReply {
  id: string;
  text: string;
  userId?: string;
  userName: string;
  userAvatar?: string;
  timestamp: Date;
}

/**
 * An annotation/discussion attached to a specific sentence
 */
export interface SentenceAnnotation {
  id: string;
  /** Reference to the sentence this annotation belongs to */
  sentenceId: string;
  /** The annotation/comment text */
  text: string;
  /** User ID who created this annotation */
  userId?: string;
  /** User who created this annotation */
  userName: string;
  userAvatar?: string;
  timestamp: Date;
  /** Optional color for the annotation */
  color?: string;
  /** Replies to this annotation */
  replies: SentenceAnnotationReply[];
  /** Whether this annotation was generated by AI */
  isAI?: boolean;
  /** AI-assigned sentence label (Method, Result, Claim, etc.) */
  aiSentenceLabel?: SentenceLabel;
  /** AI review flags */
  aiFlags?: AIReviewFlags;
}

/**
 * Text item extracted from PDF with position information
 */
export interface TextItem {
  str: string;
  x: number;
  y: number;
  width: number;
  height: number;
}

/**
 * An annotation/discussion attached to a figure or table
 */
export interface FigureTableAnnotation {
  id: string;
  /** Reference to the figure/table this annotation belongs to */
  figureTableId: string;
  /** The annotation/comment text */
  text: string;
  /** User ID who created this annotation */
  userId?: string;
  /** User who created this annotation */
  userName: string;
  userAvatar?: string;
  timestamp: Date;
  /** Optional color for the annotation */
  color?: string;
  /** Replies to this annotation */
  replies: SentenceAnnotationReply[];
  /** Whether this annotation was generated by AI */
  isAI?: boolean;
  /** AI-assigned figure/table label */
  aiFigureTableLabel?: FigureTableLabel;
  /** AI review flags */
  aiFlags?: AIReviewFlags;
}
